
language: python
python:
    - "3.5"


before_install:
    - sudo apt-get install libexpat1-dev
    - sudo apt-get install zlib1g-dev
#    - wget http://meme-suite.org/meme-software/4.12.0/meme_4.12.0.tar.gz
#    - tar zxf meme_4.12.0.tar.gz
#    - cd meme_4.12.0
#    - ./configure --prefix=$HOME/meme --with-url=http://meme-suite.org --enable-build-libxml2 --enable-build-libxslt
#    - make
#   - make test
#    - make install
#    - sudo ln -s /home/travis/meme_4.12.0/src/fimo /usr/bin
#    - fimo
    - cd

    - sudo apt-get -y install macs
    - pip install nose
    - pwd
    - ls
    - git clone https://github.com/uio-cels/OffsetBasedGraph.git
    - cd OffsetBasedGraph && git checkout develop && pip install .
    - cd
    - git clone https://github.com/uio-bmi/pyvg.git
    - cd pyvg
    - pip install .
    - pwd
    - ls
    - cd
    - ls

install:
    - ls
    - cd build/uio-bmi/graph_peak_caller
    - pip install -e .

script:
    - py.test --cov=./
    - cd tests
    - cd mhc_test_data
    - bash run_mhc_benchmarking.sh

after_success:
  - codecov
