
language: python
python:
    - "3.5"


before_install:
    - sudo apt-get install libexpat1-dev
    - sudo apt-get install zlib1g-dev
    - wget http://meme-suite.org/meme-software/4.12.0/meme_4.12.0.tar.gz
    - tar zxf meme_4.12.0.tar.gz
    - cd meme_4.12.0
    - ./configure --prefix=$HOME/meme --with-url=http://meme-suite.org --enable-build-libxml2 --enable-build-libxslt
    - make
    - make install
    - export PATH=$HOME/meme/bin:$PATH
    - cd

    - sudo apt-get -y install macs
    - pip install nose
    - pip install pytest-cov==2.4.0
    - pip install codecov
    - cd


install:
    - ls
    - cd build/uio-bmi/graph_peak_caller
    - pip install -e .

script:
    - py.test --cov=./

after_success:
    - cd /home/travis/build/uio-bmi/graph_peak_caller/
    - codecov
