
language: python
python:
    - "3.5"

before_install:
    sudo apt-get install -y python3-nose
    git clone git@github.com:uio-cels/OffsetBasedGraph.git
    cd OffsetBasedGraph && git checkout develop && pip install .

    cd
    git clone git@github.com:uio-bmi/pyvg.git
    cd pyvg
    pip install .


install:
    pip install .

script:
    cd tests && nosetests3